[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"


[project]
name = "pyinfer"
version = "0.1.0"
description = "Likelihood-based statistical inference tools"
readme = "README.md"
requires-python = ">=3.9"

authors = [
    { name = "Niko Nanda Putra Nila Lay", email = "nikonandap.lay@tum.de" },
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "numpy",
    "scipy",
    "iminuit",
]


[project.optional-dependencies]
test = [
    "pytest>=8",
]


[tool.setuptools.packages.find]
where = ["src"]
include = ["pyinfer*"]


[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra"
